updated README
postmodern/command_kit.rb pull request #45
Opened 2021-08-12 17:29 UTC by gurgeous

How about this for #39? Specifically:

1. Reordered sections, some wordsmithing
1. Redid FEATURES section
1. Badge
1. Code fences
1. Moved API to the bottom and renamed to REFERENCE

2021-08-13 20:24 UTC, postmodern requested changes
Some things I like, other things I'm not sold on. Maybe split up into multiple commits so I can cherry-pick in individual changes, like the code fences.

Also, weren't we going to copy in all of the Example code from each module into the Examples section?

2021-08-13 20:24 UTC, postmodern commented on README.md
> +* [Forum](https://github.com/postmodern/command_kit.rb/discussions) / [Issues](https://github.com/postmodern/command_kit.rb/issues)
This is a good idea. :+1: Maybe use a `|` character.

2021-08-13 20:24 UTC, postmodern commented on README.md
> +[![Build Status](https://github.com/postmodern/command_kit.rb/workflows/CI/badge.svg?branch=main)](https://github.com/postmodern/command_kit.rb/actions)
Normally I put the badges below the README `# Project` heading.

2021-08-13 20:24 UTC, postmodern commented on README.md
> +## Install
Eh, I tend to try to sell the reader on the project first then show how to install it. (Description -> Features -> Example Code -> Install). Maybe Examples could go below Install.

2021-08-13 20:24 UTC, postmodern commented on README.md
> +* **Testability** - Easy to test (ex: `MyCmd.main(arg1, arg2, options: {foo: foo}) # => 0`)
The bolded keywords are a really good idea. :+1:

2021-08-13 20:24 UTC, postmodern commented on README.md
> +* **UX** - Optional ANSI coloring. Interactive prompt for user input. Supports easily detecting the terminal size, and paging output with `less` or `more`.
Although it seems a little odd how we have concepts like Simplicity or UX along side things like Man and XDG. Maybe we should have a sub-list called "Standards" or "Integration" and list ANSI, XDG, etc.

2021-08-14 04:23 UTC, gurgeous commented
> Some things I like, other things I'm not sold on. Maybe split up into multiple commits so I can cherry-pick in individual changes, like the code fences.
> 
> Also, weren't we going to copy in all of the Example code from each module into the Examples section?

Let me take one more stab at it. It's all in one file and divided into sections so it's easy to make more changes. Not attached to any particular change. Hardest part is convincing VS Code not to autoformat 😛 

I'll do this:

1. Let's add more examples in a separate PR. I need to read those examples first.
1. Reorder badge/install/etc per feedback
1. Try again with bolded features (Standards, Integration, etc.)

2021-08-14 04:28 UTC, gurgeous commented
How about this? I have no ego on this, feel free to keep commenting and I'll keep messing with it

2021-08-17 01:22 UTC, postmodern commented
Doing some additional edits to your PR before squash-merge-signoff. Trying to think of a good word to describe all of the additional features, which can be optionally included in if you need them. Featureful? Fully Featured? Fully Loaded? Kitchen Sink? Swiss Army Knife?

2021-08-17 18:12 UTC, gurgeous commented
I like Kitchen Sink! "This stuff is useful and you might want it" but also tongue in cheek. That's usually how I try to communicate anyway 😄

2021-08-17 23:39 UTC, postmodern commented
OK manually squash merged the commits with my edits in 9831595106320260f0eebe2506a4fd64e891aeba. Was hoping that git would preserve both our authorships, but also don't want to spend too much time on the README. I rewrote the Features sections to have better Key Points (Simple, Correct, Complete, Testable) and reorganized some of the sections (Requirements should be next to Install, imo).

2021-08-17 23:39 UTC, closed without merging